{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "t80htO5lajhy",
    "outputId": "0d1e9302-e9f2-4836-9491-44e6af1a9ce7"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Libraries imported successfully!\n"
     ]
    }
   ],
   "source": [
    "# Import Libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "\n",
    "# Create necessary folders\n",
    "os.makedirs('logs', exist_ok=True)\n",
    "os.makedirs('models', exist_ok=True)\n",
    "\n",
    "print(\"Libraries imported successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "LOAD_MODELS_FIXED",
    "outputId": "0c0768da-a39b-4439-98df-dd029b3bdd8b"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "LOADING DATA AND CREATING CLUSTER PROFILES - FIXED VERSION\n",
      "Loaded scaler from: /content/scaler.pkl\n",
      "Loaded KMeans from: /content/kmeans_model.pkl\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:66: SyntaxWarning: invalid escape sequence '\\ '\n",
      "<>:66: SyntaxWarning: invalid escape sequence '\\ '\n",
      "/tmp/ipython-input-3903960383.py:66: SyntaxWarning: invalid escape sequence '\\ '\n",
      "  print(\"\\ WARNING: Some files not found!\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded data from: /content/student_study_hours_preprocessed (1).csv\n",
      "\n",
      "All files loaded successfully!\n",
      "CREATING CLUSTER PROFILES\n",
      "Loaded 80000 student records\n",
      "Using 67723 successful students\n",
      "Created 3 cluster profiles\n",
      "Habit columns: 5\n",
      "One-hot columns: 7\n",
      "\n",
      "SETUP COMPLETE! Ready to generate recommendations!\n"
     ]
    }
   ],
   "source": [
    "# FIXED: SMART FILE LOADING (Works everywhere!)\n",
    "print(\"LOADING DATA AND CREATING CLUSTER PROFILES - FIXED VERSION\")\n",
    "\n",
    "def load_models_smart():\n",
    "    \"\"\"Load models from multiple possible locations - 100% success rate!\"\"\"\n",
    "\n",
    "    # Possible locations for files\n",
    "    possible_paths = [\n",
    "        '',            # Current directory (Colab uploads here)\n",
    "        '/content/',   # Google Colab\n",
    "        './',          # Local current directory\n",
    "        '../',         # Parent directory\n",
    "        './models/',   # Models folder\n",
    "    ]\n",
    "\n",
    "    scaler = None\n",
    "    kmeans = None\n",
    "    df = None\n",
    "\n",
    "    # Try to load scaler\n",
    "    scaler_files = ['/content/scaler.pkl', 'scaler.pkl', 'scaler_model.pkl']\n",
    "    for path in possible_paths:\n",
    "        for scaler_file in scaler_files:\n",
    "            try:\n",
    "                full_path = os.path.join(path, scaler_file)\n",
    "                if os.path.exists(full_path):\n",
    "                    scaler = joblib.load(full_path)\n",
    "                    print(f\"Loaded scaler from: {full_path}\")\n",
    "                    break\n",
    "            except:\n",
    "                continue\n",
    "        if scaler is not None:\n",
    "            break\n",
    "\n",
    "    # Try to load kmeans\n",
    "    kmeans_files = ['/content/kmeans_model.pkl', 'kmeans.pkl']\n",
    "    for path in possible_paths:\n",
    "        for kmeans_file in kmeans_files:\n",
    "            try:\n",
    "                full_path = os.path.join(path, kmeans_file)\n",
    "                if os.path.exists(full_path):\n",
    "                    kmeans = joblib.load(full_path)\n",
    "                    print(f\"Loaded KMeans from: {full_path}\")\n",
    "                    break\n",
    "            except:\n",
    "                continue\n",
    "        if kmeans is not None:\n",
    "            break\n",
    "\n",
    "    # Try to load data\n",
    "    csv_files = ['/content/student_study_hours_preprocessed (1).csv', 'preprocessed_data.csv']\n",
    "    for path in possible_paths:\n",
    "        for csv_file in csv_files:\n",
    "            try:\n",
    "                full_path = os.path.join(path, csv_file)\n",
    "                if os.path.exists(full_path):\n",
    "                    df = pd.read_csv(full_path)\n",
    "                    print(f\"Loaded data from: {full_path}\")\n",
    "                    break\n",
    "            except:\n",
    "                continue\n",
    "        if df is not None:\n",
    "            break\n",
    "\n",
    "    if scaler is None or kmeans is None or df is None:\n",
    "        print(\"\\ WARNING: Some files not found!\")\n",
    "        print(\"Please upload these files:\")\n",
    "        if scaler is None:\n",
    "            print(\"  scaler.pkl or scaler (1).pkl\")\n",
    "        if kmeans is None:\n",
    "            print(\"  kmeans_model.pkl\")\n",
    "        if df is None:\n",
    "            print(\"  student_study_hours_preprocessed.csv\")\n",
    "        print(\"\\nUpload them to this notebook and run this cell again.\")\n",
    "    else:\n",
    "        print(\"\\nAll files loaded successfully!\")\n",
    "\n",
    "    return scaler, kmeans, df\n",
    "\n",
    "# Load models\n",
    "scaler, kmeans, df = load_models_smart()\n",
    "\n",
    "# Create cluster profiles (if data loaded)\n",
    "if df is not None:\n",
    "    print(\"CREATING CLUSTER PROFILES\")\n",
    "\n",
    "    # Create cluster profiles from successful students\n",
    "    successful_students = df[df['dropout_risk'] == 'No'].copy()\n",
    "    df_sorted = successful_students.sort_values(by=\"previous_gpa\", ascending=False)\n",
    "\n",
    "    # 🔧 FIXED: Added missing closing parenthesis!\n",
    "    top_df = df_sorted.groupby(\"habit_cluster\").head(\n",
    "        int(0.2 * len(successful_students) / df['habit_cluster'].nunique())\n",
    "    )  # ← THIS WAS THE BUG!\n",
    "\n",
    "    # Define features\n",
    "    habit_columns = [\n",
    "        \"study_hours_per_day\",\n",
    "        \"sleep_hours\",\n",
    "        \"social_media_hours\",\n",
    "        \"exercise_frequency\",\n",
    "        \"attendance_percentage\",\n",
    "    ]\n",
    "\n",
    "    onehot_columns = [col for col in df.columns if \"learning_style\" in col or \"study_environment\" in col]\n",
    "    cluster_profile = top_df.groupby(\"habit_cluster\")[habit_columns + onehot_columns].mean()\n",
    "\n",
    "    print(f\"Loaded {len(df)} student records\")\n",
    "    print(f\"Using {len(successful_students)} successful students\")\n",
    "    print(f\"Created {len(cluster_profile)} cluster profiles\")\n",
    "    print(f\"Habit columns: {len(habit_columns)}\")\n",
    "    print(f\"One-hot columns: {len(onehot_columns)}\")\n",
    "    print(\"\\nSETUP COMPLETE! Ready to generate recommendations!\")\n",
    "else:\n",
    "    print(\"\\nSkipping cluster profile creation (data not loaded)\")\n",
    "    cluster_profile = None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "JekTx03kajhz",
    "outputId": "63e9934a-c1fb-4abf-ec1f-76c5b4852a2e"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Helper functions defined successfully!\n"
     ]
    }
   ],
   "source": [
    "# Helper Functions\n",
    "\n",
    "def get_study_technique(cluster_id):\n",
    "    \"\"\"Return study technique based on cluster\"\"\"\n",
    "    techniques = {\n",
    "        0: \"Pomodoro Technique (25 min focus + 5 min break)\",\n",
    "        1: \"Time Blocking (90 min sessions)\",\n",
    "        2: \"Spaced Repetition (Regular review intervals)\"\n",
    "    }\n",
    "    return techniques.get(cluster_id, \"Active Recall\")\n",
    "\n",
    "\n",
    "def get_detailed_techniques(cluster_id, student_profile):\n",
    "    \"\"\"Generate detailed study techniques\"\"\"\n",
    "    techniques = []\n",
    "\n",
    "    techniques.append({\n",
    "        \"name\": \"Active Recall\",\n",
    "        \"description\": \"Test yourself instead of re-reading\",\n",
    "        \"how_to\": \"After studying, close your book and write down everything you remember\",\n",
    "        \"frequency\": \"After each study session\"\n",
    "    })\n",
    "\n",
    "    techniques.append({\n",
    "        \"name\": \"Spaced Repetition\",\n",
    "        \"description\": \"Review material at increasing intervals\",\n",
    "        \"how_to\": \"Review today's material tomorrow, then in 3 days, then in 7 days, then in 14 days\",\n",
    "        \"frequency\": \"Follow the schedule strictly\"\n",
    "    })\n",
    "\n",
    "    techniques.append({\n",
    "        \"name\": \"Pomodoro Technique\",\n",
    "        \"description\": \"Study in focused time blocks\",\n",
    "        \"how_to\": \"25 minutes intense focus + 5 minutes break. After 4 rounds, take 15-30 min break\",\n",
    "        \"frequency\": \"Use for all study sessions\"\n",
    "    })\n",
    "\n",
    "    techniques.append({\n",
    "        \"name\": \"Feynman Technique\",\n",
    "        \"description\": \"Teach concepts to learn deeply\",\n",
    "        \"how_to\": \"Explain the concept in simple terms as if teaching a 10-year-old\",\n",
    "        \"frequency\": \"Use for difficult concepts\"\n",
    "    })\n",
    "\n",
    "    if student_profile.get('attendance', 100) < 70:\n",
    "        techniques.append({\n",
    "            \"name\": \"Pre-Class Preparation\",\n",
    "            \"description\": \"Skim materials before class\",\n",
    "            \"how_to\": \"Spend 15 minutes reviewing topics before each class\",\n",
    "            \"frequency\": \"Before every class\"\n",
    "        })\n",
    "\n",
    "    return techniques\n",
    "\n",
    "\n",
    "def generate_time_management_tips(student_profile, ideal):\n",
    "    \"\"\"Generate time management recommendations\"\"\"\n",
    "    tips = []\n",
    "\n",
    "    tips.append(\"Use a daily planner or digital app (Google Calendar, Notion, Todoist)\")\n",
    "    tips.append(\"Wake up at consistent time (recommended: 6:00 AM)\")\n",
    "    tips.append(\"Use apps like Forest or Freedom to block distracting websites during study time\")\n",
    "\n",
    "    if student_profile.get('social_media', 0) > ideal['social_media_hours']:\n",
    "        tips.append(f\"Reduce social media to {ideal['social_media_hours']:.1f} hours/day (currently {student_profile.get('social_media', 0):.1f} hours)\")\n",
    "        tips.append(\"Keep phone in another room during study sessions\")\n",
    "\n",
    "    tips.append(\"Use the 2-Minute Rule: If a task takes less than 2 minutes, do it immediately\")\n",
    "    tips.append(\"Prioritize tasks using Eisenhower Matrix (Urgent/Important quadrants)\")\n",
    "    tips.append(\"Set specific daily goals (not just 'study more' but '3 chapters of Physics')\")\n",
    "\n",
    "    return tips\n",
    "\n",
    "\n",
    "def generate_wellness_routine(student_profile, ideal):\n",
    "    \"\"\"Generate wellness and self-care recommendations\"\"\"\n",
    "    routine = {}\n",
    "\n",
    "    # Sleep routine\n",
    "    target_sleep = ideal['sleep_hours']\n",
    "    current_sleep = student_profile.get('sleep_hours', 7)\n",
    "\n",
    "    routine['sleep'] = {\n",
    "        \"target\": f\"{target_sleep:.1f} hours\",\n",
    "        \"current\": f\"{current_sleep:.1f} hours\",\n",
    "        \"tips\": [\n",
    "            f\"Sleep by 10:30 PM to wake up at 6:00 AM ({target_sleep:.0f} hours)\",\n",
    "            \"No screens 1 hour before bed\",\n",
    "            \"Keep room cool and dark\",\n",
    "            \"Avoid caffeine after 4 PM\"\n",
    "        ]\n",
    "    }\n",
    "\n",
    "    # Exercise routine\n",
    "    target_exercise = ideal['exercise_frequency']\n",
    "    current_exercise = student_profile.get('exercise', 3)\n",
    "\n",
    "    routine['exercise'] = {\n",
    "        \"target\": f\"{target_exercise:.0f} times/week\",\n",
    "        \"current\": f\"{current_exercise:.0f} times/week\",\n",
    "        \"recommended_activities\": [\n",
    "            \"Morning jog/walk (30 min)\",\n",
    "            \"Yoga or stretching (20 min)\",\n",
    "            \"Gym workout (45 min)\",\n",
    "            \"Cycling or sports (1 hour)\",\n",
    "            \"Swimming (30 min)\"\n",
    "        ],\n",
    "        \"tips\": [\n",
    "            \"Exercise before studying to boost focus\",\n",
    "            \"Even 10-minute walks help during study breaks\"\n",
    "        ]\n",
    "    }\n",
    "\n",
    "    # Nutrition\n",
    "    routine['nutrition'] = {\n",
    "        \"tips\": [\n",
    "            \"Eat protein-rich breakfast (eggs, oats, nuts)\",\n",
    "            \"Drink 8 glasses of water daily\",\n",
    "            \"Healthy snacks during study (fruits, nuts)\",\n",
    "            \"Avoid heavy meals before studying\",\n",
    "            \"Limit coffee to 1-2 cups/day\"\n",
    "        ]\n",
    "    }\n",
    "\n",
    "    # Mental health\n",
    "    routine['mental_health'] = {\n",
    "        \"stress_management\": [\n",
    "            \"5-minute meditation before studying\",\n",
    "            \"Journal for 10 minutes daily\",\n",
    "            \"Talk to friends/family when stressed\",\n",
    "            \"Listen to focus music (lo-fi, classical)\",\n",
    "            \"Spend time outdoors daily\"\n",
    "        ]\n",
    "    }\n",
    "\n",
    "    return routine\n",
    "\n",
    "print(\"Helper functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "ygCtMHsqajhz",
    "outputId": "b7fad15b-6b14-40f5-8604-0be4931299dd"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Study routine generator defined!\n"
     ]
    }
   ],
   "source": [
    "# Study Routine Generator\n",
    "\n",
    "def generate_study_routine(student_profile, cluster_id):\n",
    "    \"\"\"\n",
    "    Generate a personalized weekly study routine\n",
    "\n",
    "    Args:\n",
    "        student_profile: Dictionary with current student stats\n",
    "        cluster_id: Student's cluster assignment\n",
    "\n",
    "    Returns:\n",
    "        Dictionary with detailed study routine\n",
    "    \"\"\"\n",
    "\n",
    "    ideal = cluster_profile.loc[cluster_id]\n",
    "    target_study_hours = ideal['study_hours_per_day']\n",
    "\n",
    "    # Determine optimal study times based on cluster\n",
    "    if cluster_id == 0:  # High-performing balanced students\n",
    "        study_blocks = [\n",
    "            {\"time\": \"06:00 AM - 08:00 AM\", \"duration\": 2, \"type\": \"Morning Deep Work\", \"subjects\": \"Core subjects (Math, Science)\"},\n",
    "            {\"time\": \"02:00 PM - 04:00 PM\", \"duration\": 2, \"type\": \"Afternoon Review\", \"subjects\": \"Review and practice\"},\n",
    "            {\"time\": \"07:00 PM - 09:00 PM\", \"duration\": 2, \"type\": \"Evening Study\", \"subjects\": \"Assignments and projects\"}\n",
    "        ]\n",
    "    elif cluster_id == 1:  # Moderate performers\n",
    "        study_blocks = [\n",
    "            {\"time\": \"08:00 AM - 10:00 AM\", \"duration\": 2, \"type\": \"Morning Study\", \"subjects\": \"Priority subjects\"},\n",
    "            {\"time\": \"04:00 PM - 06:00 PM\", \"duration\": 2, \"type\": \"Evening Study\", \"subjects\": \"Review and homework\"}\n",
    "        ]\n",
    "    else:  # Cluster 2 - Need improvement\n",
    "        study_blocks = [\n",
    "            {\"time\": \"09:00 AM - 11:00 AM\", \"duration\": 2, \"type\": \"Focused Study\", \"subjects\": \"Weak areas\"},\n",
    "            {\"time\": \"05:00 PM - 07:00 PM\", \"duration\": 2, \"type\": \"Practice Session\", \"subjects\": \"Problem-solving\"}\n",
    "        ]\n",
    "\n",
    "    # Generate weekly routine\n",
    "    days = [\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\"]\n",
    "    weekly_routine = {}\n",
    "\n",
    "    for day in days:\n",
    "        if day in [\"Saturday\", \"Sunday\"]:\n",
    "            daily_hours = min(target_study_hours * 0.7, 5)\n",
    "            daily_blocks = study_blocks[:2]\n",
    "        else:\n",
    "            daily_hours = target_study_hours\n",
    "            daily_blocks = study_blocks\n",
    "\n",
    "        weekly_routine[day] = {\n",
    "            \"total_hours\": round(daily_hours, 1),\n",
    "            \"study_blocks\": daily_blocks,\n",
    "            \"breaks\": \"10 min break after each hour\",\n",
    "            \"focus_technique\": get_study_technique(cluster_id)\n",
    "        }\n",
    "\n",
    "    # Get additional components\n",
    "    study_techniques = get_detailed_techniques(cluster_id, student_profile)\n",
    "    time_management = generate_time_management_tips(student_profile, ideal)\n",
    "    wellness_routine = generate_wellness_routine(student_profile, ideal)\n",
    "\n",
    "    return {\n",
    "        \"weekly_schedule\": weekly_routine,\n",
    "        \"study_techniques\": study_techniques,\n",
    "        \"time_management_tips\": time_management,\n",
    "        \"wellness_routine\": wellness_routine,\n",
    "        \"target_metrics\": {\n",
    "            \"daily_study_hours\": round(target_study_hours, 1),\n",
    "            \"weekly_study_hours\": round(target_study_hours * 7, 1),\n",
    "            \"sleep_hours\": round(ideal['sleep_hours'], 1),\n",
    "            \"exercise_per_week\": int(ideal['exercise_frequency']),\n",
    "            \"social_media_limit\": round(ideal['social_media_hours'], 1)\n",
    "        }\n",
    "    }\n",
    "\n",
    "print(\"Study routine generator defined!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "BgdVCsdKajhz",
    "outputId": "04c91098-a8d7-4c12-de08-dbd8878a1742"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Action plan and progress tracking functions defined!\n"
     ]
    }
   ],
   "source": [
    "# Action Plan & Progress Tracking\n",
    "\n",
    "def generate_action_plan(priority_score):\n",
    "    \"\"\"Generate week-by-week action plan\"\"\"\n",
    "\n",
    "    if priority_score >= 10:\n",
    "        timeline = \"8-12 weeks\"\n",
    "    elif priority_score >= 6:\n",
    "        timeline = \"6-8 weeks\"\n",
    "    else:\n",
    "        timeline = \"4-6 weeks\"\n",
    "\n",
    "    action_plan = {\n",
    "        \"timeline\": timeline,\n",
    "        \"phases\": []\n",
    "    }\n",
    "\n",
    "    # Phase 1\n",
    "    action_plan[\"phases\"].append({\n",
    "        \"week\": \"1-2\",\n",
    "        \"focus\": \"Foundation Building\",\n",
    "        \"goals\": [\n",
    "            \"Establish consistent sleep schedule\",\n",
    "            \"Increase study time by 1 hour/day\",\n",
    "            \"Attend all classes\",\n",
    "            \"Reduce social media by 30 minutes/day\"\n",
    "        ]\n",
    "    })\n",
    "\n",
    "    # Phase 2\n",
    "    action_plan[\"phases\"].append({\n",
    "        \"week\": \"3-4\",\n",
    "        \"focus\": \"Habit Reinforcement\",\n",
    "        \"goals\": [\n",
    "            \"Maintain Phase 1 improvements\",\n",
    "            \"Add 1 more hour of study time\",\n",
    "            \"Implement Pomodoro technique\",\n",
    "            \"Start exercise routine (3x/week)\"\n",
    "        ]\n",
    "    })\n",
    "\n",
    "    # Phase 3\n",
    "    action_plan[\"phases\"].append({\n",
    "        \"week\": \"5-6\",\n",
    "        \"focus\": \"Optimization\",\n",
    "        \"goals\": [\n",
    "            \"Reach target study hours\",\n",
    "            \"Master active recall technique\",\n",
    "            \"Achieve 90%+ attendance\",\n",
    "            \"Balance all wellness metrics\"\n",
    "        ]\n",
    "    })\n",
    "\n",
    "    # Phase 4\n",
    "    action_plan[\"phases\"].append({\n",
    "        \"week\": \"7+\",\n",
    "        \"focus\": \"Maintenance & Excellence\",\n",
    "        \"goals\": [\n",
    "            \"Maintain all target metrics\",\n",
    "            \"Help peers with study strategies\",\n",
    "            \"Continuously improve weak subjects\"\n",
    "        ]\n",
    "    })\n",
    "\n",
    "    return action_plan\n",
    "\n",
    "\n",
    "def generate_progress_metrics(current, ideal):\n",
    "    \"\"\"Generate trackable progress metrics\"\"\"\n",
    "\n",
    "    metrics = []\n",
    "\n",
    "    metrics.append({\n",
    "        \"metric\": \"Study Hours/Day\",\n",
    "        \"current\": round(current['study_hours'], 1),\n",
    "        \"target\": round(ideal['study_hours_per_day'], 1),\n",
    "        \"unit\": \"hours\",\n",
    "        \"tracking_method\": \"Daily log in planner\"\n",
    "    })\n",
    "\n",
    "    metrics.append({\n",
    "        \"metric\": \"Sleep Hours/Day\",\n",
    "        \"current\": round(current['sleep_hours'], 1),\n",
    "        \"target\": round(ideal['sleep_hours'], 1),\n",
    "        \"unit\": \"hours\",\n",
    "        \"tracking_method\": \"Sleep tracking app\"\n",
    "    })\n",
    "\n",
    "    metrics.append({\n",
    "        \"metric\": \"Attendance Rate\",\n",
    "        \"current\": round(current['attendance'], 1),\n",
    "        \"target\": round(ideal['attendance_percentage'], 1),\n",
    "        \"unit\": \"%\",\n",
    "        \"tracking_method\": \"Class attendance record\"\n",
    "    })\n",
    "\n",
    "    metrics.append({\n",
    "        \"metric\": \"Social Media Usage\",\n",
    "        \"current\": round(current['social_media'], 1),\n",
    "        \"target\": round(ideal['social_media_hours'], 1),\n",
    "        \"unit\": \"hours/day\",\n",
    "        \"tracking_method\": \"Screen time app\"\n",
    "    })\n",
    "\n",
    "    metrics.append({\n",
    "        \"metric\": \"Exercise Frequency\",\n",
    "        \"current\": round(current['exercise'], 0),\n",
    "        \"target\": round(ideal['exercise_frequency'], 0),\n",
    "        \"unit\": \"times/week\",\n",
    "        \"tracking_method\": \"Fitness tracker\"\n",
    "    })\n",
    "\n",
    "    return metrics\n",
    "\n",
    "print(\"Action plan and progress tracking functions defined!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "II3Br9fJajh0",
    "outputId": "9d54522f-56fe-4bee-8ce2-cc1318b17451"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Main recommendation function defined!\n"
     ]
    }
   ],
   "source": [
    "# Main Function: Get Personalized Study Plan (Existing Students)\n",
    "\n",
    "def get_personalized_study_plan(student_id):\n",
    "    \"\"\"\n",
    "    Generate complete personalized study plan for existing student\n",
    "\n",
    "    Args:\n",
    "        student_id: Student ID from database\n",
    "\n",
    "    Returns:\n",
    "        Complete study plan dictionary\n",
    "    \"\"\"\n",
    "\n",
    "    if student_id not in df['student_id'].values:\n",
    "        return {\"error\": \"Student ID not found\"}\n",
    "\n",
    "    # Get student data\n",
    "    student = df[df['student_id'] == student_id].iloc[0]\n",
    "    cluster = student['habit_cluster']\n",
    "    ideal = cluster_profile.loc[cluster]\n",
    "\n",
    "    # Create student profile\n",
    "    student_profile = {\n",
    "        'study_hours': student['study_hours_per_day'],\n",
    "        'sleep_hours': student['sleep_hours'],\n",
    "        'attendance': student['attendance_percentage'],\n",
    "        'social_media': student['social_media_hours'],\n",
    "        'exercise': student['exercise_frequency']\n",
    "    }\n",
    "\n",
    "    # Generate gap analysis\n",
    "    recommendations = []\n",
    "    priority_score = 0\n",
    "\n",
    "    if student['study_hours_per_day'] < ideal['study_hours_per_day']:\n",
    "        diff = round(ideal['study_hours_per_day'] - student['study_hours_per_day'], 1)\n",
    "        recommendations.append({\n",
    "            'category': 'Study Time',\n",
    "            'priority': 'High',\n",
    "            'current': round(student['study_hours_per_day'], 1),\n",
    "            'target': round(ideal['study_hours_per_day'], 1),\n",
    "            'gap': diff,\n",
    "            'message': f\"Increase study hours by {diff} hours/day\"\n",
    "        })\n",
    "        priority_score += 3\n",
    "\n",
    "    if student['sleep_hours'] < ideal['sleep_hours']:\n",
    "        diff = round(ideal['sleep_hours'] - student['sleep_hours'], 1)\n",
    "        recommendations.append({\n",
    "            'category': 'Sleep',\n",
    "            'priority': 'High',\n",
    "            'current': round(student['sleep_hours'], 1),\n",
    "            'target': round(ideal['sleep_hours'], 1),\n",
    "            'gap': diff,\n",
    "            'message': f\"Get {diff} more hours of sleep\"\n",
    "        })\n",
    "        priority_score += 3\n",
    "\n",
    "    if student['attendance_percentage'] < ideal['attendance_percentage']:\n",
    "        diff = round(ideal['attendance_percentage'] - student['attendance_percentage'], 1)\n",
    "        recommendations.append({\n",
    "            'category': 'Attendance',\n",
    "            'priority': 'High',\n",
    "            'current': round(student['attendance_percentage'], 1),\n",
    "            'target': round(ideal['attendance_percentage'], 1),\n",
    "            'gap': diff,\n",
    "            'message': f\"Improve attendance by {diff}%\"\n",
    "        })\n",
    "        priority_score += 3\n",
    "\n",
    "    if student['social_media_hours'] > ideal['social_media_hours']:\n",
    "        diff = round(student['social_media_hours'] - ideal['social_media_hours'], 1)\n",
    "        recommendations.append({\n",
    "            'category': 'Digital Wellness',\n",
    "            'priority': 'Medium',\n",
    "            'current': round(student['social_media_hours'], 1),\n",
    "            'target': round(ideal['social_media_hours'], 1),\n",
    "            'gap': diff,\n",
    "            'message': f\"Reduce social media by {diff} hours/day\"\n",
    "        })\n",
    "        priority_score += 2\n",
    "\n",
    "    if student['exercise_frequency'] < ideal['exercise_frequency']:\n",
    "        diff = round(ideal['exercise_frequency'] - student['exercise_frequency'], 1)\n",
    "        recommendations.append({\n",
    "            'category': 'Physical Health',\n",
    "            'priority': 'Medium',\n",
    "            'current': round(student['exercise_frequency'], 1),\n",
    "            'target': round(ideal['exercise_frequency'], 1),\n",
    "            'gap': diff,\n",
    "            'message': f\"Exercise {diff} more times/week\"\n",
    "        })\n",
    "        priority_score += 2\n",
    "\n",
    "    # Generate complete study routine\n",
    "    study_routine = generate_study_routine(student_profile, cluster)\n",
    "\n",
    "    # Risk assessment\n",
    "    risk_status = \"At Risk\" if student['dropout_risk'] == 'Yes' else \"Low Risk\"\n",
    "\n",
    "    # Complete response\n",
    "    return {\n",
    "        'student_info': {\n",
    "            'student_id': int(student_id),\n",
    "            'cluster': int(cluster),\n",
    "            'cluster_name': f\"Cluster {cluster}\",\n",
    "            'risk_status': risk_status,\n",
    "            'priority_score': priority_score\n",
    "        },\n",
    "        'current_habits': student_profile,\n",
    "        'gap_analysis': recommendations,\n",
    "        'personalized_study_routine': study_routine,\n",
    "        'action_plan': generate_action_plan(priority_score),\n",
    "        'progress_tracking': generate_progress_metrics(student_profile, ideal)\n",
    "    }\n",
    "\n",
    "print(\"Main recommendation function defined!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "kNxKdopkajh0",
    "outputId": "8350a7c6-d97b-4fb4-d317-720beb7e2dea"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "New student prediction function defined!\n"
     ]
    }
   ],
   "source": [
    "# Predict for New Students\n",
    "\n",
    "def predict_for_new_student(new_student_data):\n",
    "    \"\"\"\n",
    "    Accept new student data and provide predictions + recommendations\n",
    "\n",
    "    Args:\n",
    "        new_student_data: Dictionary with student information\n",
    "\n",
    "    Returns:\n",
    "        Complete analysis and personalized study plan\n",
    "    \"\"\"\n",
    "\n",
    "    # Required fields\n",
    "    required_fields = [\n",
    "        'study_hours_per_day', 'social_media_hours', 'netflix_hours',\n",
    "        'attendance_percentage', 'sleep_hours', 'screen_time',\n",
    "        'time_management_score', 'exercise_frequency'\n",
    "    ]\n",
    "\n",
    "    # Validate input\n",
    "    for field in required_fields:\n",
    "        if field not in new_student_data:\n",
    "            return {\"error\": f\"Missing required field: {field}\"}\n",
    "\n",
    "    # Check if models are loaded\n",
    "    if scaler is None or kmeans is None:\n",
    "        return {\"error\": \"Models not loaded. Please ensure scaler.pkl and kmeans_model.pkl exist.\"}\n",
    "\n",
    "    try:\n",
    "        # Prepare data for clustering\n",
    "        clustering_features = [\n",
    "            'study_hours_per_day', 'social_media_hours', 'netflix_hours',\n",
    "            'attendance_percentage', 'sleep_hours', 'screen_time', 'time_management_score'\n",
    "        ]\n",
    "\n",
    "        X_cluster = np.array([[new_student_data[f] for f in clustering_features]])\n",
    "        X_cluster_scaled = scaler.transform(X_cluster)\n",
    "\n",
    "        # Predict cluster\n",
    "        cluster = kmeans.predict(X_cluster_scaled)[0]\n",
    "\n",
    "        # Get ideal profile for cluster\n",
    "        ideal = cluster_profile.loc[cluster]\n",
    "\n",
    "        # Create student profile\n",
    "        student_profile = {\n",
    "            'study_hours': new_student_data['study_hours_per_day'],\n",
    "            'sleep_hours': new_student_data['sleep_hours'],\n",
    "            'attendance': new_student_data['attendance_percentage'],\n",
    "            'social_media': new_student_data['social_media_hours'],\n",
    "            'exercise': new_student_data['exercise_frequency']\n",
    "        }\n",
    "\n",
    "        # Generate recommendations\n",
    "        recommendations = []\n",
    "        priority_score = 0\n",
    "\n",
    "        if new_student_data['study_hours_per_day'] < ideal['study_hours_per_day']:\n",
    "            diff = round(ideal['study_hours_per_day'] - new_student_data['study_hours_per_day'], 1)\n",
    "            recommendations.append({\n",
    "                'category': 'Study Time',\n",
    "                'priority': 'High',\n",
    "                'current': round(new_student_data['study_hours_per_day'], 1),\n",
    "                'target': round(ideal['study_hours_per_day'], 1),\n",
    "                'gap': diff,\n",
    "                'message': f\"Increase study hours by {diff} hours/day\"\n",
    "            })\n",
    "            priority_score += 3\n",
    "\n",
    "        if new_student_data['sleep_hours'] < ideal['sleep_hours']:\n",
    "            diff = round(ideal['sleep_hours'] - new_student_data['sleep_hours'], 1)\n",
    "            recommendations.append({\n",
    "                'category': 'Sleep',\n",
    "                'priority': 'High',\n",
    "                'current': round(new_student_data['sleep_hours'], 1),\n",
    "                'target': round(ideal['sleep_hours'], 1),\n",
    "                'gap': diff,\n",
    "                'message': f\"Get {diff} more hours of sleep\"\n",
    "            })\n",
    "            priority_score += 3\n",
    "\n",
    "        if new_student_data['attendance_percentage'] < ideal['attendance_percentage']:\n",
    "            diff = round(ideal['attendance_percentage'] - new_student_data['attendance_percentage'], 1)\n",
    "            recommendations.append({\n",
    "                'category': 'Attendance',\n",
    "                'priority': 'High',\n",
    "                'current': round(new_student_data['attendance_percentage'], 1),\n",
    "                'target': round(ideal['attendance_percentage'], 1),\n",
    "                'gap': diff,\n",
    "                'message': f\"Improve attendance by {diff}%\"\n",
    "            })\n",
    "            priority_score += 3\n",
    "\n",
    "        if new_student_data['social_media_hours'] > ideal['social_media_hours']:\n",
    "            diff = round(new_student_data['social_media_hours'] - ideal['social_media_hours'], 1)\n",
    "            recommendations.append({\n",
    "                'category': 'Digital Wellness',\n",
    "                'priority': 'Medium',\n",
    "                'current': round(new_student_data['social_media_hours'], 1),\n",
    "                'target': round(ideal['social_media_hours'], 1),\n",
    "                'gap': diff,\n",
    "                'message': f\"Reduce social media by {diff} hours/day\"\n",
    "            })\n",
    "            priority_score += 2\n",
    "\n",
    "        if new_student_data['exercise_frequency'] < ideal['exercise_frequency']:\n",
    "            diff = round(ideal['exercise_frequency'] - new_student_data['exercise_frequency'], 1)\n",
    "            recommendations.append({\n",
    "                'category': 'Physical Health',\n",
    "                'priority': 'Medium',\n",
    "                'current': round(new_student_data['exercise_frequency'], 1),\n",
    "                'target': round(ideal['exercise_frequency'], 1),\n",
    "                'gap': diff,\n",
    "                'message': f\"Exercise {diff} more times/week\"\n",
    "            })\n",
    "            priority_score += 2\n",
    "\n",
    "        # Generate study routine\n",
    "        study_routine = generate_study_routine(student_profile, cluster)\n",
    "\n",
    "        # Estimate risk\n",
    "        if priority_score >= 10:\n",
    "            risk_status = \"High Risk\"\n",
    "        elif priority_score >= 6:\n",
    "            risk_status = \"Moderate Risk\"\n",
    "        else:\n",
    "            risk_status = \"Low Risk\"\n",
    "\n",
    "        return {\n",
    "            'student_info': {\n",
    "                'cluster': int(cluster),\n",
    "                'cluster_name': f\"Cluster {cluster}\",\n",
    "                'risk_status': risk_status,\n",
    "                'priority_score': priority_score\n",
    "            },\n",
    "            'current_habits': student_profile,\n",
    "            'gap_analysis': recommendations,\n",
    "            'personalized_study_routine': study_routine,\n",
    "            'action_plan': generate_action_plan(priority_score),\n",
    "            'progress_tracking': generate_progress_metrics(student_profile, ideal)\n",
    "        }\n",
    "\n",
    "    except Exception as e:\n",
    "        return {\"error\": f\"Prediction failed: {str(e)}\"}\n",
    "\n",
    "print(\"New student prediction function defined!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "8u1cObaYajh0",
    "outputId": "27347b33-a6c6-4262-d723-c81f5571438d"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Display function defined!\n"
     ]
    }
   ],
   "source": [
    "# Display Function\n",
    "\n",
    "def display_study_plan(plan):\n",
    "    \"\"\"Display the study plan in a formatted way\"\"\"\n",
    "\n",
    "    if 'error' in plan:\n",
    "        print(f\"Error: {plan['error']}\")\n",
    "        return\n",
    "\n",
    "    print(\"PERSONALIZED STUDY PLAN - STUDYTRACK AI\")\n",
    "\n",
    "\n",
    "    # Student Info\n",
    "    info = plan['student_info']\n",
    "    student_id_str = str(info.get('student_id', 'New Student'))\n",
    "    print(f\"\\nStudent ID: {student_id_str}\")\n",
    "    print(f\"Cluster: {info['cluster_name']}\")\n",
    "    print(f\"Risk Status: {info['risk_status']}\")\n",
    "    print(f\"Priority Score: {info['priority_score']}/15\")\n",
    "\n",
    "    # Current vs Target\n",
    "    if plan['gap_analysis']:\n",
    "        print(\"CURRENT HABITS vs TARGETS\")\n",
    "\n",
    "        for rec in plan['gap_analysis']:\n",
    "            print(f\"\\n{rec['category']}\")\n",
    "            print(f\"   Current: {rec['current']} | Target: {rec['target']} | Gap: {rec['gap']}\")\n",
    "\n",
    "    # Weekly Schedule\n",
    "    print(\"WEEKLY STUDY SCHEDULE\")\n",
    "\n",
    "    routine = plan['personalized_study_routine']\n",
    "    print(f\"\\nTarget: {routine['target_metrics']['daily_study_hours']} hours/day\")\n",
    "    print(f\"Weekly Total: {routine['target_metrics']['weekly_study_hours']} hours\")\n",
    "\n",
    "    print(\"\\nSample Daily Schedule (Monday-Friday):\")\n",
    "    sample_day = routine['weekly_schedule']['Monday']\n",
    "    for block in sample_day['study_blocks']:\n",
    "        print(f\" {block['time']}: {block['type']} ({block['duration']} hrs)\")\n",
    "        print(f\" Focus: {block['subjects']}\")\n",
    "\n",
    "    print(f\"\\nBreaks: {sample_day['breaks']}\")\n",
    "    print(f\"Technique: {sample_day['focus_technique']}\")\n",
    "\n",
    "    # Study Techniques\n",
    "    print(\"RECOMMENDED STUDY TECHNIQUES\")\n",
    "\n",
    "    for i, tech in enumerate(routine['study_techniques'][:3], 1):\n",
    "        print(f\"\\n{i}. {tech['name']}\")\n",
    "        print(f\"   What: {tech['description']}\")\n",
    "        print(f\"   How: {tech['how_to']}\")\n",
    "        print(f\"   When: {tech['frequency']}\")\n",
    "\n",
    "    # Time Management\n",
    "    print(\"TIME MANAGEMENT TIPS\")\n",
    "\n",
    "    for tip in routine['time_management_tips'][:5]:\n",
    "        print(f\"\\n  {tip}\")\n",
    "\n",
    "    # Wellness\n",
    "    print(\"WELLNESS ROUTINE\")\n",
    "\n",
    "    wellness = routine['wellness_routine']\n",
    "    print(f\"\\nSleep: {wellness['sleep']['target']} (currently {wellness['sleep']['current']})\")\n",
    "    for tip in wellness['sleep']['tips'][:3]:\n",
    "        print(f\"   • {tip}\")\n",
    "\n",
    "    print(f\"\\nExercise: {wellness['exercise']['target']} (currently {wellness['exercise']['current']})\")\n",
    "    for activity in wellness['exercise']['recommended_activities'][:3]:\n",
    "        print(f\"   • {activity}\")\n",
    "\n",
    "    # Action Plan\n",
    "    print(\"ACTION PLAN\")\n",
    "\n",
    "    action = plan['action_plan']\n",
    "    print(f\"\\nTimeline: {action['timeline']}\")\n",
    "\n",
    "    for phase in action['phases'][:2]:\n",
    "        print(f\"\\n Week {phase['week']}: {phase['focus']}\")\n",
    "        for goal in phase['goals']:\n",
    "            print(f\"   - {goal}\")\n",
    "\n",
    "    print(\"Your success journey starts now! Track daily progress.\")\n",
    "\n",
    "print(\"Display function defined!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "NngCBLMJp27M",
    "outputId": "f42d851c-b8cc-42da-eb25-bf9d51fe17de"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "LOADING DATA FOR RECOMMENDATION ENGINE\n",
      "Loaded: /content/student_study_hours_preprocessed (1).csv (80000 records)\n",
      "Creating cluster profiles...\n",
      "Created 3 cluster profiles\n",
      "READY! Now run your test code.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "print(\"LOADING DATA FOR RECOMMENDATION ENGINE\")\n",
    "\n",
    "# Load CSV data\n",
    "csv_files = [\n",
    "    '/content/student_study_hours_preprocessed (1).csv',\n",
    "    '/content/student_study_hours_preprocessed.csv',\n",
    "    '/content/student_study_hours_preprocessed (1).csv'\n",
    "]\n",
    "\n",
    "df = None\n",
    "for csv_file in csv_files:\n",
    "    if os.path.exists(csv_file):\n",
    "        df = pd.read_csv(csv_file)\n",
    "        print(f\"Loaded: {csv_file} ({len(df)} records)\")\n",
    "        break\n",
    "\n",
    "if df is None:\n",
    "    print(\"ERROR: Upload 'student_study_hours_preprocessed.csv' first!\")\n",
    "    print(\"   1. Click folder icon on left\")\n",
    "    print(\"   2. Upload your CSV file\")\n",
    "    print(\"   3. Run this cell again\")\n",
    "else:\n",
    "    # Create cluster profiles\n",
    "    print(\"Creating cluster profiles...\")\n",
    "    successful_students = df[df['dropout_risk'] == 'No'].copy()\n",
    "    df_sorted = successful_students.sort_values(by=\"previous_gpa\", ascending=False)\n",
    "\n",
    "    top_df = df_sorted.groupby(\"habit_cluster\").head(\n",
    "        int(0.2 * len(successful_students) / df['habit_cluster'].nunique())\n",
    "    )\n",
    "\n",
    "    habit_columns = [\n",
    "        \"study_hours_per_day\", \"sleep_hours\", \"social_media_hours\",\n",
    "        \"exercise_frequency\", \"attendance_percentage\"\n",
    "    ]\n",
    "\n",
    "    onehot_columns = [col for col in df.columns if \"learning_style\" in col or \"study_environment\" in col]\n",
    "    cluster_profile = top_df.groupby(\"habit_cluster\")[habit_columns + onehot_columns].mean()\n",
    "\n",
    "    print(f\"Created {len(cluster_profile)} cluster profiles\")\n",
    "    print(\"READY! Now run your test code.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "vDUmWOwnajh1",
    "outputId": "0ec602d6-e004-4846-a862-8f8ea8d3e19e"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TESTING WITH EXISTING STUDENT\n",
      "PERSONALIZED STUDY PLAN - STUDYTRACK AI\n",
      "\n",
      "Student ID: 100059\n",
      "Cluster: Cluster 1\n",
      "Risk Status: At Risk\n",
      "Priority Score: 13/15\n",
      "CURRENT HABITS vs TARGETS\n",
      "\n",
      "Study Time\n",
      "   Current: 2.2 | Target: 3.7 | Gap: 1.5\n",
      "\n",
      "Sleep\n",
      "   Current: 6.6 | Target: 7.1 | Gap: 0.5\n",
      "\n",
      "Attendance\n",
      "   Current: 49.3 | Target: 70.9 | Gap: 21.6\n",
      "\n",
      "Digital Wellness\n",
      "   Current: 1.7 | Target: 1.1 | Gap: 0.6\n",
      "\n",
      "Physical Health\n",
      "   Current: 2 | Target: 3.8 | Gap: 1.8\n",
      "WEEKLY STUDY SCHEDULE\n",
      "\n",
      "Target: 3.7 hours/day\n",
      "Weekly Total: 25.9 hours\n",
      "\n",
      "Sample Daily Schedule (Monday-Friday):\n",
      " 08:00 AM - 10:00 AM: Morning Study (2 hrs)\n",
      " Focus: Priority subjects\n",
      " 04:00 PM - 06:00 PM: Evening Study (2 hrs)\n",
      " Focus: Review and homework\n",
      "\n",
      "Breaks: 10 min break after each hour\n",
      "Technique: Time Blocking (90 min sessions)\n",
      "RECOMMENDED STUDY TECHNIQUES\n",
      "\n",
      "1. Active Recall\n",
      "   What: Test yourself instead of re-reading\n",
      "   How: After studying, close your book and write down everything you remember\n",
      "   When: After each study session\n",
      "\n",
      "2. Spaced Repetition\n",
      "   What: Review material at increasing intervals\n",
      "   How: Review today's material tomorrow, then in 3 days, then in 7 days, then in 14 days\n",
      "   When: Follow the schedule strictly\n",
      "\n",
      "3. Pomodoro Technique\n",
      "   What: Study in focused time blocks\n",
      "   How: 25 minutes intense focus + 5 minutes break. After 4 rounds, take 15-30 min break\n",
      "   When: Use for all study sessions\n",
      "TIME MANAGEMENT TIPS\n",
      "\n",
      "  Use a daily planner or digital app (Google Calendar, Notion, Todoist)\n",
      "\n",
      "  Wake up at consistent time (recommended: 6:00 AM)\n",
      "\n",
      "  Use apps like Forest or Freedom to block distracting websites during study time\n",
      "\n",
      "  Reduce social media to 1.1 hours/day (currently 1.7 hours)\n",
      "\n",
      "  Keep phone in another room during study sessions\n",
      "WELLNESS ROUTINE\n",
      "\n",
      "Sleep: 7.1 hours (currently 6.6 hours)\n",
      "   • Sleep by 10:30 PM to wake up at 6:00 AM (7 hours)\n",
      "   • No screens 1 hour before bed\n",
      "   • Keep room cool and dark\n",
      "\n",
      "Exercise: 4 times/week (currently 2 times/week)\n",
      "   • Morning jog/walk (30 min)\n",
      "   • Yoga or stretching (20 min)\n",
      "   • Gym workout (45 min)\n",
      "ACTION PLAN\n",
      "\n",
      "Timeline: 8-12 weeks\n",
      "\n",
      " Week 1-2: Foundation Building\n",
      "   - Establish consistent sleep schedule\n",
      "   - Increase study time by 1 hour/day\n",
      "   - Attend all classes\n",
      "   - Reduce social media by 30 minutes/day\n",
      "\n",
      " Week 3-4: Habit Reinforcement\n",
      "   - Maintain Phase 1 improvements\n",
      "   - Add 1 more hour of study time\n",
      "   - Implement Pomodoro technique\n",
      "   - Start exercise routine (3x/week)\n",
      "Your success journey starts now! Track daily progress.\n"
     ]
    }
   ],
   "source": [
    "# Test with existing student\n",
    "print(\"TESTING WITH EXISTING STUDENT\")\n",
    "\n",
    "test_student_id = 100059\n",
    "complete_plan = get_personalized_study_plan(test_student_id)\n",
    "display_study_plan(complete_plan)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "cuvnLCTTajh1",
    "outputId": "df06f302-459c-4d65-c19b-dcb19aee7604"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TESTING WITH NEW STUDENT DATA\n",
      "\n",
      "New student analysis complete!\n",
      "Cluster: 2\n",
      "Risk: High Risk\n",
      "Priority Score: 13/15\n",
      "Recommendations: 5 areas to improve\n",
      "DISPLAYING COMPLETE PLAN\n",
      "PERSONALIZED STUDY PLAN - STUDYTRACK AI\n",
      "\n",
      "Student ID: New Student\n",
      "Cluster: Cluster 2\n",
      "Risk Status: High Risk\n",
      "Priority Score: 13/15\n",
      "CURRENT HABITS vs TARGETS\n",
      "\n",
      "Study Time\n",
      "   Current: 3.5 | Target: 3.6 | Gap: 0.1\n",
      "\n",
      "Sleep\n",
      "   Current: 6.0 | Target: 7.1 | Gap: 1.1\n",
      "\n",
      "Attendance\n",
      "   Current: 65.0 | Target: 72.5 | Gap: 7.5\n",
      "\n",
      "Digital Wellness\n",
      "   Current: 4.0 | Target: 3.7 | Gap: 0.3\n",
      "\n",
      "Physical Health\n",
      "   Current: 2 | Target: 3.7 | Gap: 1.7\n",
      "WEEKLY STUDY SCHEDULE\n",
      "\n",
      "Target: 3.6 hours/day\n",
      "Weekly Total: 25.2 hours\n",
      "\n",
      "Sample Daily Schedule (Monday-Friday):\n",
      " 09:00 AM - 11:00 AM: Focused Study (2 hrs)\n",
      " Focus: Weak areas\n",
      " 05:00 PM - 07:00 PM: Practice Session (2 hrs)\n",
      " Focus: Problem-solving\n",
      "\n",
      "Breaks: 10 min break after each hour\n",
      "Technique: Spaced Repetition (Regular review intervals)\n",
      "RECOMMENDED STUDY TECHNIQUES\n",
      "\n",
      "1. Active Recall\n",
      "   What: Test yourself instead of re-reading\n",
      "   How: After studying, close your book and write down everything you remember\n",
      "   When: After each study session\n",
      "\n",
      "2. Spaced Repetition\n",
      "   What: Review material at increasing intervals\n",
      "   How: Review today's material tomorrow, then in 3 days, then in 7 days, then in 14 days\n",
      "   When: Follow the schedule strictly\n",
      "\n",
      "3. Pomodoro Technique\n",
      "   What: Study in focused time blocks\n",
      "   How: 25 minutes intense focus + 5 minutes break. After 4 rounds, take 15-30 min break\n",
      "   When: Use for all study sessions\n",
      "TIME MANAGEMENT TIPS\n",
      "\n",
      "  Use a daily planner or digital app (Google Calendar, Notion, Todoist)\n",
      "\n",
      "  Wake up at consistent time (recommended: 6:00 AM)\n",
      "\n",
      "  Use apps like Forest or Freedom to block distracting websites during study time\n",
      "\n",
      "  Reduce social media to 3.7 hours/day (currently 4.0 hours)\n",
      "\n",
      "  Keep phone in another room during study sessions\n",
      "WELLNESS ROUTINE\n",
      "\n",
      "Sleep: 7.1 hours (currently 6.0 hours)\n",
      "   • Sleep by 10:30 PM to wake up at 6:00 AM (7 hours)\n",
      "   • No screens 1 hour before bed\n",
      "   • Keep room cool and dark\n",
      "\n",
      "Exercise: 4 times/week (currently 2 times/week)\n",
      "   • Morning jog/walk (30 min)\n",
      "   • Yoga or stretching (20 min)\n",
      "   • Gym workout (45 min)\n",
      "ACTION PLAN\n",
      "\n",
      "Timeline: 8-12 weeks\n",
      "\n",
      " Week 1-2: Foundation Building\n",
      "   - Establish consistent sleep schedule\n",
      "   - Increase study time by 1 hour/day\n",
      "   - Attend all classes\n",
      "   - Reduce social media by 30 minutes/day\n",
      "\n",
      " Week 3-4: Habit Reinforcement\n",
      "   - Maintain Phase 1 improvements\n",
      "   - Add 1 more hour of study time\n",
      "   - Implement Pomodoro technique\n",
      "   - Start exercise routine (3x/week)\n",
      "Your success journey starts now! Track daily progress.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# Test with new student\n",
    "print(\"TESTING WITH NEW STUDENT DATA\")\n",
    "\n",
    "# New student data\n",
    "new_student = {\n",
    "    'age': 20,\n",
    "    'study_hours_per_day': 3.5,\n",
    "    'social_media_hours': 4.0,\n",
    "    'netflix_hours': 2.0,\n",
    "    'attendance_percentage': 65.0,\n",
    "    'sleep_hours': 6.0,\n",
    "    'exercise_frequency': 2,\n",
    "    'mental_health_rating': 6.5,\n",
    "    'stress_level': 7.0,\n",
    "    'time_management_score': 4.5,\n",
    "    'screen_time': 9.5\n",
    "}\n",
    "\n",
    "new_plan = predict_for_new_student(new_student)\n",
    "\n",
    "if 'error' in new_plan:\n",
    "    print(f\"\\nError: {new_plan['error']}\")\n",
    "else:\n",
    "    print(\"\\nNew student analysis complete!\")\n",
    "    print(f\"Cluster: {new_plan['student_info']['cluster']}\")\n",
    "    print(f\"Risk: {new_plan['student_info']['risk_status']}\")\n",
    "    print(f\"Priority Score: {new_plan['student_info']['priority_score']}/15\")\n",
    "    print(f\"Recommendations: {len(new_plan['gap_analysis'])} areas to improve\")\n",
    "\n",
    "    print(\"DISPLAYING COMPLETE PLAN\")\n",
    "    display_study_plan(new_plan)"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
