# Generated by Django 6.0 on 2026-01-06 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_dataset_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_hours_per_day", models.FloatField()),
                ("attendance_percentage", models.FloatField()),
                ("sleep_hours", models.FloatField()),
                ("stress_level", models.FloatField()),
                ("exercise_frequency", models.FloatField()),
                ("dropout_risk", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
            ],
        ),
    ]
