# Generated by Django 6.0 on 2026-01-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="recommendation",
            field=models.TextField(blank=True),
        ),
    ]
