# Generated by Django 6.0 on 2026-01-06 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_studentprofile_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
            ),
        ),
    ]
